name: flutter_test_ci_cd
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.1.1
  cupertino_icons: ^0.1.3
  provider: ^4.0.4
  flutter_mobx: ^1.1.0

  get_it: ^4.0.1
  injectable: ^0.3.0

dev_dependencies:
  injectable_generator: ^0.3.3
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
